# Generated by Django 3.2.4 on 2021-06-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
