# Generated by Django 3.2.4 on 2021-06-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTest', '0002_hello_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
