# Generated by Django 3.2.4 on 2021-06-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTest', '0003_alter_hello_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
    ]
