# Generated by Django 3.2.4 on 2021-06-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTest', '0006_auto_20210617_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
